### ISSUE TITLE
the code is not complete

### ISSUE THREAD

**Issue by yongnuan** [PacktPublishing/Machine-Learning-for-Time-Series-with-Python#1]
Hi Ben,

I have high expectation on your book and am very excited to learn. However, the codes published on Github is incomplete. For example, in chapter 2, where are the codes from page 52 to 53 especially page 53? I am very interested to know how you did the code in page 53. Also some codes in jupyter notebook are not explained either in notebook and book.  I am kind of disappointed. Could you please republish your complete jupyter notebook? Thanks

**Comment by benman1** [comment]
Hi!
First: thanks for your interest in the book. I am very sorry to hear you
are so disappointed. Please note that some differences are intended -
usually the notebooks go beyond the chapters - in a few cases the chapters
add something new. I'll have a look at what's missing and get back to you.

**Comment by yongnuan** [comment]
Thanks Ben. It is a great book and I have been waiting for a long time for it in Canada.

**Comment by yongnuan** [comment]
Hi Ben

Sorry today I was so hurry to make this comment. I think you can delete the post.   I think this book is great and I have already at chapter 7. I really enjoy it. Yes some of sections I hope have more detail explanation. But overall so far it is pretty good. I will write some good review later at Amazon after finishing the book. 

Thanks for a great book!

Regards

Yongnuan

**Comment by yongnuan** [comment]
Hi Ben

I am so keen to finish your book and I made it to last chapter. I would say
this is a fantastic book and meet my original high expectations. Thank you!

However i am still struggling with installing time_series from your git.
Is it possible that you can help me take a look at it?

Here is the error trace:  Thank you so much if you can help. I appreciate
it.  Regards, Yongnuan

!pip install git+https://github.com/benman1/time-series.git

Collecting git+https://github.com/benman1/time-series.git
  Cloning https://github.com/benman1/time-series.git to
c:\users\yongn\appdata\local\temp\pip-req-build-ydhben6i

  Running command git clone -q
https://github.com/benman1/time-series.git
'C:\Users\yongn\AppData\Local\Temp\pip-req-build-ydhben6i'
ERROR: pip's dependency resolver does not currently take into account
all the packages that are installed. This behaviour is the source of
the following dependency conflicts.
woodwork 0.9.0 requires pandas>=1.3.0, but you have pandas 1.2.5 which
is incompatible.
sktime 0.8.1 requires statsmodels<=0.12.1, but you have statsmodels
0.12.2 which is incompatible.
greykite 0.2.0 requires plotly<4,>=3.10.0, but you have plotly 5.3.1
which is incompatible.
featuretools 1.1.0 requires pandas<2.0.0,>=1.3.0, but you have pandas
1.2.5 which is incompatible.

Requirement already satisfied: numpy>=1.19.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
time-series==0.2) (1.21.2)
Collecting pandas~=1.2.4
  Using cached pandas-1.2.5-cp38-cp38-win_amd64.whl (9.3 MB)
Requirement already satisfied: tensorflow>2.5.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
time-series==0.2) (2.7.0)
Requirement already satisfied: pytest in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (6.2.5)
Requirement already satisfied: requests~=2.25.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
time-series==0.2) (2.25.1)
Collecting pyreadr~=0.4.2
  Using cached pyreadr-0.4.2-cp38-cp38-win_amd64.whl (1.1 MB)
Requirement already satisfied: scikit-learn~=0.24.1 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (0.24.2)
Collecting statsmodels~=0.12.2
  Using cached statsmodels-0.12.2-cp38-none-win_amd64.whl (9.4 MB)
Collecting fastcache~=1.1.0
  Using cached fastcache-1.1.0-cp38-cp38-win_amd64.whl
Collecting tensorflow-addons
  Using cached tensorflow_addons-0.15.0-cp38-cp38-win_amd64.whl (753 kB)
Collecting gpflow~=2.2.1
  Using cached gpflow-2.2.1-py3-none-any.whl (271 kB)
Requirement already satisfied: scipy~=1.6.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (1.6.3)
Collecting joblib~=1.0.1
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Requirement already satisfied: setuptools>=41.0.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (58.0.4)
Collecting deprecated
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Requirement already satisfied: packaging in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (21.0)
Requirement already satisfied: tensorflow-probability>0.10.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.14.1)
Requirement already satisfied: typing-extensions in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
gpflow~=2.2.1->time-series==0.2) (3.7.4.3)
Collecting multipledispatch>=0.6
  Using cached multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Requirement already satisfied: tabulate in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.8.9)
Requirement already satisfied: six in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
multipledispatch>=0.6->gpflow~=2.2.1->time-series==0.2) (1.16.0)
Requirement already satisfied: python-dateutil>=2.7.3 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pandas~=1.2.4->time-series==0.2) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pandas~=1.2.4->time-series==0.2) (2021.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (2.6)
Requirement already satisfied: chardet<5,>=3.0.2 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (3.0.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
scikit-learn~=0.24.1->time-series==0.2) (2.2.0)
Requirement already satisfied: patsy>=0.5 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
statsmodels~=0.12.2->time-series==0.2) (0.5.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.22.0)
Requirement already satisfied: google-pasta>=0.1.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.2.0)
Requirement already satisfied: astunparse>=1.6.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.6.3)
Requirement already satisfied: gast<0.5.0,>=0.2.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.4.0)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.12)
Requirement already satisfied: termcolor>=1.1.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.1.2)
Requirement already satisfied: protobuf>=3.9.2 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.17.2)
Requirement already satisfied: tensorboard~=2.6 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.34.1)
Requirement already satisfied: h5py>=2.9.0 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.1.0)
Requirement already satisfied: absl-py>=0.4.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.13.0)
Requirement already satisfied: libclang>=9.0.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (12.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.3.0)
Requirement already satisfied: tensorflow-estimator<2.8,~=2.7.0rc0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: wrapt>=1.11.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.12.1)
Requirement already satisfied: wheel<1.0,>=0.32.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.37.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0
in c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (0.6.1)
Requirement already satisfied: werkzeug>=0.11.15 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (2.0.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (0.4.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (1.6.0)
Requirement already satisfied: markdown>=2.6.8 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (3.3.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (1.33.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(3.1.1)
Requirement already satisfied: cloudpickle>=1.3 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(2.0.0)
Requirement already satisfied: decorator in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(5.1.0)
Requirement already satisfied: dm-tree in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(0.1.6)
Requirement already satisfied: pyparsing>=2.0.2 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
packaging->gpflow~=2.2.1->time-series==0.2) (3.0.4)
Requirement already satisfied: atomicwrites>=1.0 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.4.0)
Requirement already satisfied: colorama in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pytest->time-series==0.2) (0.4.4)
Requirement already satisfied: attrs>=19.2.0 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pytest->time-series==0.2) (21.2.0)
Requirement already satisfied: py>=1.8.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.11.0)
Requirement already satisfied: toml in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
pytest->time-series==0.2) (0.10.2)

fancyimpute 0.6.0 requires keras==2.4.3, but you have keras 2.7.0
which is incompatible.
fancyimpute 0.6.0 requires numpy==1.19.5, but you have numpy 1.21.2
which is incompatible.
fancyimpute 0.6.0 requires tensorflow==2.5, but you have tensorflow
2.7.0 which is incompatible.
alibi-detect 0.7.3 requires tensorflow<2.7.0,>=2.0.0, but you have
tensorflow 2.7.0 which is incompatible.
alibi-detect 0.7.3 requires tensorflow-probability<0.13.0,>=0.8.0, but
you have tensorflow-probability 0.14.1 which is incompatible.
prophet 1.0.1 requires cmdstanpy==0.9.68, but you have cmdstanpy 0.9.5
which is incompatible.
gluonts 0.8.1 requires typing-extensions~=3.10.0.0, but you have
typing-extensions 3.7.4.3 which is incompatible.

Requirement already satisfied: iniconfig in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.0.0)
Requirement already satisfied: typeguard>=2.7 in
c:\users\yongn\miniconda3\envs\forecast\lib\site-packages (from
tensorflow-addons->time-series==0.2) (2.13.0)
Installing collected packages: pandas, multipledispatch, joblib,
deprecated, dataclasses, tensorflow-addons, statsmodels, pyreadr,
gpflow, fastcache
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.4
    Uninstalling pandas-1.3.4:
      Successfully uninstalled pandas-1.3.4
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.13.0
    Uninstalling statsmodels-0.13.0:
      Successfully uninstalled statsmodels-0.13.0
Successfully installed dataclasses-0.6 deprecated-1.2.13
fastcache-1.1.0 gpflow-2.2.1 joblib-1.0.1 multipledispatch-0.6.0
pandas-1.2.5 pyreadr-0.4.2 statsmodels-0.12.2 tensorflow-addons-0.15.0

**Comment by benman1** [comment]
Hi Yongnuan
Sorry for not getting back earlier - it's been a very busy period for me. Thanks a lot for your nice words. I was very happy to read this.

It seems that you have lots of libraries in versions incompatible with the requirements. I think what should be easiest in your case would be to create a new python environment and install everything into it. There should be some explanations for this in chapter 1, but here's the rundown:

1. Create a new python environment the terminal (not python yet):
```bash
python3 -m venv .env
```

2. Run jupyter notebook/labs from within the environment:
```bash
source .env/bin/activate
jupyter notebook
```

Then run the install with pip as before. 

Please let me know how this goes.

**Comment by yongnuan** [comment]
Thanks you so much Ben, I made a 5 starts review at amazon.ca, check it
out. Thanks for a great book.

https://www.amazon.ca/Machine-Learning-Time-Python-state/dp/1801819629/ref=sxts_rp_s3_0?cv_ct_cx=time+series+python&keywords=time+sereies+pyuthon&pd_rd_i=1801819629&pd_rd_r=c4b98807-1e80-4341-a547-376c21729972&pd_rd_w=xoBZx&pd_rd_wg=F3h4E&pf_rd_p=372505a5-6a58-475a-86d4-6ef2cad8c79f&pf_rd_r=ASED5E9B78DY66GPPBR2&psc=1&qid=1637554761&sr=1-3-f0029781-b79b-4b60-9cb0-eeda4dea34d6

For installing time-series library from you Github, I still have an issue
even after creating a new conda environment, here is the error. I like your
time-series library. Hope you can give me some guidance on fixing this
error. Thank you so much.

---------------------------------------------------------------------------ModuleNotFoundError
                      Traceback (most recent call
last)~\AppData\Local\Temp/ipykernel_35936/1218231198.py in <module>
  1 from time_series.dataset.utils import get_energy_demand----> 2
from time_series.dataset.time_series import TrainingDataSet      3
  4 train_df = get_energy_demand()      5 tds =
TrainingDataSet(train_df)
~\miniconda3\lib\site-packages\time_series\dataset\time_series.py in
<module>      8       9 if version.parse(np.__version__) >=
version.parse("1.20.0"):---> 10     from numpy.typing.np_types import
ArrayLike     11 else:     12     from typing import Union
ModuleNotFoundError: No module named 'numpy.typing.np_types

**Comment by benman1** [comment]
Hi Yongnuan
Thanks so much for the review! Much appreciated.

Thanks also for reporting this! I've pushed a change that should fix this - I think I had mistyped the numpy version number that includes a feature, typing support - I had 1.20 instead of 1.21, [the version that includes typing]. So this should be fixed now. Please give it another try.

Thanks again!
Ben

**Comment by yongnuan** [comment]
Hi Ben

I tired and still the same problem about ModuleNotFoundError: No module
named 'numpy.typing.np_types'

The way I did are as follow:

in my conda new environment or inside jupyter notebook, I did

pip install git+https://github.com/benman1/time-series.git

then it shows most of are satisfied as shown below.

Collecting git+https://github.com/benman1/time-series.git
  Cloning https://github.com/benman1/time-series.git to
c:\users\yongn\appdata\local\temp\pip-req-build-z8a5c608
Requirement already satisfied: numpy>=1.19.0 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(1.21.4)

  Running command git clone -q
https://github.com/benman1/time-series.git
'C:\Users\yongn\AppData\Local\Temp\pip-req-build-z8a5c608'

Requirement already satisfied: pandas~=1.2.4 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(1.2.5)
Requirement already satisfied: tensorflow>2.5.0 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(2.7.0)
Requirement already satisfied: pytest in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (6.2.5)
Requirement already satisfied: requests~=2.25.1 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(2.25.1)
Requirement already satisfied: pyreadr~=0.4.2 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(0.4.2)
Requirement already satisfied: scikit-learn~=0.24.1 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (0.24.2)
Requirement already satisfied: statsmodels~=0.12.2 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(0.12.2)
Requirement already satisfied: fastcache~=1.1.0 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(1.1.0)
Requirement already satisfied: tensorflow-addons in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(0.15.0)
Requirement already satisfied: gpflow~=2.2.1 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(2.2.1)
Requirement already satisfied: scipy~=1.6.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
time-series==0.2) (1.6.3)
Requirement already satisfied: joblib~=1.0.1 in
c:\users\yongn\miniconda3\lib\site-packages (from time-series==0.2)
(1.0.1)
Requirement already satisfied: deprecated in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (1.2.13)
Requirement already satisfied: tabulate in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.8.9)
Requirement already satisfied: typing-extensions in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
gpflow~=2.2.1->time-series==0.2) (3.7.4.3)
Requirement already satisfied: tensorflow-probability>0.10.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.15.0)
Requirement already satisfied: packaging in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (21.0)
Requirement already satisfied: multipledispatch>=0.6 in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.6.0)
Requirement already satisfied: setuptools>=41.0.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (58.0.4)
Requirement already satisfied: dataclasses in
c:\users\yongn\miniconda3\lib\site-packages (from
gpflow~=2.2.1->time-series==0.2) (0.6)
Requirement already satisfied: six in
c:\users\yongn\miniconda3\lib\site-packages (from
multipledispatch>=0.6->gpflow~=2.2.1->time-series==0.2) (1.16.0)
Requirement already satisfied: python-dateutil>=2.7.3 in
c:\users\yongn\miniconda3\lib\site-packages (from
pandas~=1.2.4->time-series==0.2) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in
c:\users\yongn\miniconda3\lib\site-packages (from
pandas~=1.2.4->time-series==0.2) (2021.1)
Requirement already satisfied: chardet<5,>=3.0.2 in
c:\users\yongn\miniconda3\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in
c:\users\yongn\miniconda3\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in
c:\users\yongn\miniconda3\lib\site-packages (from
requests~=2.25.1->time-series==0.2) (2.10)
Requirement already satisfied: threadpoolctl>=2.0.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
scikit-learn~=0.24.1->time-series==0.2) (2.2.0)
Requirement already satisfied: patsy>=0.5 in
c:\users\yongn\miniconda3\lib\site-packages (from
statsmodels~=0.12.2->time-series==0.2) (0.5.1)
Requirement already satisfied: termcolor>=1.1.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.1.2)
Requirement already satisfied: wrapt>=1.11.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.12.1)
Requirement already satisfied: tensorflow-estimator<2.8,~=2.7.0rc0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.2.0)
Requirement already satisfied: gast<0.5.0,>=0.2.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.4.0)
Requirement already satisfied: h5py>=2.9.0 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.1.0)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: astunparse>=1.6.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.6.3)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.12)
Requirement already satisfied: absl-py>=0.4.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.0.0)
Requirement already satisfied: tensorboard~=2.6 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (2.7.0)
Requirement already satisfied: wheel<1.0,>=0.32.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.37.0)
Requirement already satisfied: libclang>=9.0.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (12.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow>2.5.0->time-series==0.2) (1.34.1)
Requirement already satisfied: protobuf>=3.9.2 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (3.19.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow>2.5.0->time-series==0.2) (0.22.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0
in c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (0.6.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (3.3.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (1.8.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (2.3.3)
Requirement already satisfied: werkzeug>=0.11.15 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2) (2.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in
c:\users\yongn\miniconda3\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in
c:\users\yongn\miniconda3\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(1.3.0)
Requirement already satisfied: importlib-metadata>=4.4 in
c:\users\yongn\miniconda3\lib\site-packages (from
markdown>=2.6.8->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(4.8.1)
Requirement already satisfied: zipp>=0.5 in
c:\users\yongn\miniconda3\lib\site-packages (from
importlib-metadata>=4.4->markdown>=2.6.8->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(3.5.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in
c:\users\yongn\miniconda3\lib\site-packages (from
pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>2.5.0->time-series==0.2)
(3.1.1)
Requirement already satisfied: cloudpickle>=1.3 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(1.6.0)
Requirement already satisfied: dm-tree in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(0.1.6)
Requirement already satisfied: decorator in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow-probability>0.10.0->gpflow~=2.2.1->time-series==0.2)
(5.0.9)
Requirement already satisfied: pyparsing>=2.0.2 in
c:\users\yongn\miniconda3\lib\site-packages (from
packaging->gpflow~=2.2.1->time-series==0.2) (2.4.7)
Requirement already satisfied: pluggy<2.0,>=0.12 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.0.0)
Requirement already satisfied: py>=1.8.2 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.11.0)
Requirement already satisfied: colorama in
c:\users\yongn\miniconda3\lib\site-packages (from
pytest->time-series==0.2) (0.4.4)
Requirement already satisfied: atomicwrites>=1.0 in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.4.0)
Requirement already satisfied: iniconfig in
c:\users\yongn\appdata\roaming\python\python38\site-packages (from
pytest->time-series==0.2) (1.1.1)
Requirement already satisfied: toml in
c:\users\yongn\miniconda3\lib\site-packages (from
pytest->time-series==0.2) (0.10.2)
Requirement already satisfied: attrs>=19.2.0 in
c:\users\yongn\miniconda3\lib\site-packages (from
pytest->time-series==0.2) (21.2.0)
Requirement already satisfied: typeguard>=2.7 in
c:\users\yongn\miniconda3\lib\site-packages (from
tensorflow-addons->time-series==0.2) (2.13.0)

**Comment by benman1** [comment]
Hi Yongnuan
That's weird - so I see your numpy version is 1.21.4 - and I've checked
again the numpy release notes and the numpy code on github: there should be
a numpy typing module.

What could be is that you haven't restarted your kernel. If you restart
your kernel, does it work then?

If not, I can just remove the numpy typing part and it should work.

Thanks for checking!
Ben

----

**Comment by yongnuan** [comment]
Hi Ben,

Here is the screenshot of the error. How do you check if I have not started
the kernel yet? or how to start the kernel? Thanks.. Yongnuan

[image: image.png]

**Comment by benman1** [comment]
Hi Yongnuan
I can't see your image - it's not attached to the comment, I think. You might have to upload it on github directly when you write a comment.

[Restarting a kernel](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html#executing-a-notebook) is clicking **Kernel** > **Restart** from the Jupyter menu.
Cheers
Ben

**Comment by yongnuan** [comment]
Hi Ben

I tried restarting the kernel and it still has the same error. Thanks

Yongnuan

**Comment by benman1** [comment]
Hi Yongnuan
Sorry for taking longer than usual. I couldn't reproduce your error, but I have removed all references to `numpy.typing`. So if you download the code again (do the `pip install` command again) and reload your kernel it should run.
Please let me know.

**Comment by yongnuan** [comment]
Hi Ben,

Thanks for getting back to me. Yes it finally works! I am so glad to see
that. I love this time-series library you developed.  I appreciate it.

Have a great week! Take care and all the best!

Regards

Yongnuan
